name: Feature request
description: File a proposal for new feature, improvement.
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new feature, improvement proposal.
  - type: textarea
    id: message
    attributes:
      label: New feature, improvement proposal
    validations:
      required: true
