<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.kbuntrock.openapi.it</groupId>
    <artifactId>openapi-basic-it-jaxrs</artifactId>
    <version>23.5.2</version>
    <name>Basic integration test Jax-RS</name>
    <description>Basic description test</description>

    <properties>
        <java.version>17</java.version>
        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <openapi-plugin-project-version>0.0.33-SNAPSHOT</openapi-plugin-project-version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <artifactId>javax.servlet-api</artifactId>
            <groupId>javax.servlet</groupId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <artifactId>validation-api</artifactId>
            <groupId>javax.validation</groupId>
            <version>2.0.1.Final</version>
        </dependency>
        <dependency>
            <artifactId>javax.ws.rs-api</artifactId>
            <groupId>javax.ws.rs</groupId>
            <version>2.1.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.github.kbuntrock</groupId>
                <artifactId>openapi-maven-plugin</artifactId>
                <version>${openapi-plugin-project-version}</version>
                <configuration>
                    <analytics>false</analytics>
                    <apiConfiguration>
                        <library>jaxrs</library>
                    </apiConfiguration>
                    <apis>
                        <api>
                            <locations>
                                <location>io.github.kbuntrock.sample.enpoint</location>
                            </locations>
                        </api>
                    </apis>
                    <javadocConfiguration>
                        <scanLocations>
                            <project>src/main/java</project>
                        </scanLocations>
                    </javadocConfiguration>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>documentation</goal>
                        </goals>
                        <id>documentation</id>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>
