
name: publish documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-doc:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - name: Regular checkout
      uses: actions/checkout@v4
      with:
        ref: doc
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm
    - name: Install dependencies
      working-directory: docs
      run: npm ci
    - name: Build website
      working-directory: docs
      run: npm run build

    - name: Merge and push
      run: |
        echo "Auto-merge ${{ github.ref_name }} to doc branch"
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch --tags origin
        git add docs/build -f
        git merge ${{ github.ref_name }} -m "Auto-merge ${{ github.ref_name }} to doc branch"
        git push