name: Test deployment

on:
  pull_request:
    branches:
      - dev

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: docs/package-lock.json
          node-version: 22
          cache: npm

      - name: Install dependencies
        working-directory: docs
        run: npm ci
      
      - name: Test build website
        working-directory: docs
        run: npm run build